use std::{borrow::Cow, fmt::Display};

use super::{
    mora_dict::INTO_STR,
    mora_enum::MoraEnum,
    phoneme::{mora_to_phoneme, Consonant, Vowel},
    QUESTION, QUOTATION, TOUTEN,
};

use bitcode::{Decode, Encode};
use serde::{Deserialize, Serialize};

/// Do not access moras and accent directly unless through [`pron`] macro.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, Debug, Default)]
pub struct Moras(pub Cow<'static, [Mora]>);

impl Moras {
    pub fn new(moras: Vec<Mora>) -> Self {
        Self(Cow::Owned(moras))
    }
}

impl AsRef<[Mora]> for Moras {
    fn as_ref(&self) -> &[Mora] {
        &self.0
    }
}
impl AsMut<[Mora]> for Moras {
    fn as_mut(&mut self) -> &mut [Mora] {
        self.0.to_mut()
    }
}

/// bitcode::Encode and Decode implementations for Moras.
///
/// This is generated by bitcode_derive::Encode and Decode, but we need to write it manually because Moras contains Cow,
/// which cannot be automatically derived.
#[doc(hidden)]
mod moras_codec {
    use crate::pronunciation::{Mora, Moras};

    impl bitcode::__private::Encode for Moras {
        type Encoder = MorasEncoder;
    }

    #[derive(Default)]
    pub struct MorasEncoder {
        f0: <Vec<Mora> as bitcode::__private::Encode>::Encoder,
    }
    impl bitcode::__private::Encoder<Moras> for MorasEncoder {
        fn encode(&mut self, v: &Moras) {
            let Moras(f0) = v;
            self.f0.encode(&f0.to_vec());
        }
        fn encode_vectored<'v>(&mut self, i: impl Iterator<Item = &'v Moras> + Clone)
        where
            Moras: 'v,
        {
            for v in i {
                self.f0.encode(&v.as_ref().to_vec());
            }
        }
    }
    impl bitcode::__private::Buffer for MorasEncoder {
        fn collect_into(&mut self, out: &mut bitcode::__private::Vec<u8>) {
            self.f0.collect_into(out);
        }
        fn reserve(&mut self, __additional: ::core::num::NonZeroUsize) {
            self.f0.reserve(__additional);
        }
    }

    impl<'de> bitcode::__private::Decode<'de> for Moras {
        type Decoder = MorasDecoder<'de>;
    }

    #[derive(Default)]
    pub struct MorasDecoder<'de> {
        f0: <Vec<Mora> as bitcode::__private::Decode<'de>>::Decoder,
    }
    impl<'de> bitcode::__private::View<'de> for MorasDecoder<'de> {
        fn populate(
            &mut self,
            input: &mut &'de [u8],
            __length: usize,
        ) -> bitcode::__private::Result<()> {
            self.f0.populate(input, __length)?;
            Ok(())
        }
    }
    impl<'de> bitcode::__private::Decoder<'de, Moras> for MorasDecoder<'de> {
        fn decode(&mut self) -> Moras {
            use std::borrow::Cow;
            let f0 = self.f0.decode();
            Moras(Cow::Owned(f0))
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Encode, Decode)]
pub struct Mora {
    pub mora_enum: MoraEnum,
    pub is_voiced: bool,
}

impl Mora {
    pub fn phonemes(&self) -> (Option<Consonant>, Option<Vowel>) {
        mora_to_phoneme(self)
    }

    pub fn convert_to_voiced_sound(&mut self) {
        self.mora_enum = match self.mora_enum {
            MoraEnum::Ka => MoraEnum::Ga,
            MoraEnum::Ki => MoraEnum::Gi,
            MoraEnum::Ku => MoraEnum::Gu,
            MoraEnum::Ke => MoraEnum::Ge,
            MoraEnum::Ko => MoraEnum::Go,
            MoraEnum::Kya => MoraEnum::Gya,
            MoraEnum::Kyu => MoraEnum::Gyu,
            MoraEnum::Kyo => MoraEnum::Gyo,
            MoraEnum::Kye => MoraEnum::Gye,
            MoraEnum::Sa => MoraEnum::Za,
            MoraEnum::Shi => MoraEnum::Ji,
            MoraEnum::Su => MoraEnum::Zu,
            MoraEnum::Se => MoraEnum::Ze,
            MoraEnum::So => MoraEnum::Zo,
            MoraEnum::Swi => MoraEnum::Zwi,
            MoraEnum::Sha => MoraEnum::Ja,
            MoraEnum::Shu => MoraEnum::Ju,
            MoraEnum::Sho => MoraEnum::Jo,
            MoraEnum::She => MoraEnum::Je,
            MoraEnum::Ta => MoraEnum::Da,
            MoraEnum::Chi => MoraEnum::Di,
            MoraEnum::Tsu => MoraEnum::Du,
            MoraEnum::Te => MoraEnum::De,
            MoraEnum::To => MoraEnum::Do,
            MoraEnum::Tha => MoraEnum::Dha,
            MoraEnum::Thi => MoraEnum::Dhi,
            MoraEnum::Thu => MoraEnum::Dhu,
            MoraEnum::Twu => MoraEnum::Dwu,
            MoraEnum::Tho => MoraEnum::Dho,
            MoraEnum::Ha => MoraEnum::Ba,
            MoraEnum::Hi => MoraEnum::Bi,
            MoraEnum::Fu => MoraEnum::Bu,
            MoraEnum::He => MoraEnum::Be,
            MoraEnum::Ho => MoraEnum::Bo,
            MoraEnum::Hya => MoraEnum::Bya,
            MoraEnum::Hyu => MoraEnum::Byu,
            MoraEnum::Hye => MoraEnum::Bye,
            MoraEnum::Hyo => MoraEnum::Byo,
            others => others,
        }
    }
    pub fn convert_to_semivoiced_sound(&mut self) {
        self.mora_enum = match self.mora_enum {
            MoraEnum::Ha => MoraEnum::Pa,
            MoraEnum::Hi => MoraEnum::Pi,
            MoraEnum::Fu => MoraEnum::Pu,
            MoraEnum::He => MoraEnum::Pe,
            MoraEnum::Ho => MoraEnum::Po,
            MoraEnum::Hya => MoraEnum::Pya,
            MoraEnum::Hyu => MoraEnum::Pyu,
            MoraEnum::Hye => MoraEnum::Pye,
            MoraEnum::Hyo => MoraEnum::Pyo,
            others => others,
        }
    }
}

impl Display for Mora {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mora = match self.mora_enum {
            MoraEnum::Question => QUESTION,
            MoraEnum::Touten => TOUTEN,
            mora_enum => INTO_STR.get(&mora_enum).unwrap(),
        };
        let suffix = if self.is_voiced { "" } else { QUOTATION };
        write!(f, "{}{}", mora, suffix)
    }
}
